# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_auto_20161009_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
